run-core-gpu-tests: added output verification

diff --git a/run-core-gpu-tests/action.yml b/run-core-gpu-tests/action.yml
--- a/run-core-gpu-tests/action.yml
+++ b/run-core-gpu-tests/action.yml
@@ -32,3 +32,17 @@ runs:
         # Run Diligent Core GPU Tests
         chmod +x "${{github.action_path}}/run_core_gpu_tests.sh"
         "${{github.action_path}}/run_core_gpu_tests.sh"
+
+    - name: Verify Test Output
+      env:
+        INPUT_MODE:    ${{inputs.mode}}
+        INPUT_USE_DXC: ${{inputs.use_dxc}}
+      shell: bash
+      run: |
+        # Verify Test Output
+        chmod +x "${{github.action_path}}/verify_test_output.sh"
+        EXIT_CODE=0
+        "${{github.action_path}}/verify_test_output.sh" || EXIT_CODE=$?
+        if [[ "$EXIT_CODE" != "0" ]]; then
+          echo "::error:: Core GPU tests output verification failed! Please examine it to find mismatches."
+        fi
